### ISSUE TITLE
Support of AMD64

### ISSUE THREAD

**Issue by xaionaro** [cojocar/bin2llvm#5]
Is support of AMD64 planned?

```
[xaionaro@void helloworld]$ readelf -h /tmp/helloworld/helloworld 
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x44e250
  Start of program headers:          64 (bytes into file)
  Start of section headers:          456 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         23
  Section header string table index: 3
[xaionaro@void helloworld]$ docker run -v /tmp:/tmp --rm -t docker.io/cojocar/bin2llvm /bin/bash -c "/usr/local/bin2llvm/bin/bin2llvm.py --file /tmp/helloworld/helloworld"
Press Ctrl+C
INFO:bin2llvm:Using /tmp/bin2llvm-3jkewR as temp_dir
Traceback (most recent call last):
  File "/usr/local/bin2llvm/bin/bin2llvm.py", line 855, in <module>
    main()
  File "/usr/local/bin2llvm/bin/bin2llvm.py", line 631, in main
    cfg, isThumbIn = do_elf(args.file[0], args.temp_dir)
  File "/usr/local/bin2llvm/bin/bin2llvm-pymodules/elf_parser.py", line 51, in do_elf
    raise Exception("Architecture not supported")
Exception: Architecture not supported
```

**Comment by cojocar** [comment]
Hi @xaionaro ,

there is no plan to support or test AMD64 architecture. That being said, parts of the code are agnostic to what architecture is in use, for example the qemu translation should already support AMD64. The post processing of the harvested code is the one that needs to be (slightly) adapted for a new architecture. I'd be more than happy to go over such a pull request.
